export const socketConstant = {
  CONNECTING_TO_SOCKET: 'CONNECTING_TO_SOCKET',
  CONNECTING_SUCCESS: 'CONNECTING_SUCCESS',
  CONNECTING_FAIL: 'CONNECTING_FAIL',
};
export const buildConstants = {
    BUILD_CONNECTION: 'BUILD_CONNECTION',
    BUILD_CONNECTION_SUCCESS: 'BUILD_CONNECTION_SUCCESS',
    BUILD_CONNECTION_FAIL: 'BUILD_CONNECTION_FAIL',

    GET_ALL_ACTIVE_ADMIN_SUCCESS: 'GET_ALL_ACTIVE_ADMIN_SUCCESS',
    GET_ALL_ACTIVE_ADMIN_FAIL: 'GET_ALL_ACTIVE_ADMIN_FAIL',
    
    NEW_CONNECTION_SUCCESS: 'NEW_CONNECTION_SUCCESS',
};

export const paymentMethodConstant = {
  QR_PAYMENT_REQUEST : 'QR_PAYMENT_REQUEST',
  QR_PAYMENT_SCAN_SUCCESS: 'QR_PAYMENT_SCAN_SUCCESS',
  QR_PAYMENT_SCAN_FAIL: 'QR_PAYMENT_SCAN_FAIL',

  QR_LOGIN_PASS_SUCCESS: 'QR_LOGIN_PASS_SUCCESS',
  QR_LOGIN_PASS_FAIL: 'QR_LOGIN_PASS_FAIL',

  QR_LOGIN_PASS_SEND_SMS_SUCCESS: 'QR_LOGIN_PASS_SEND_SMS_SUCCESS',
  QR_LOGIN_PASS_SEND_SMS_FAIL: 'QR_LOGIN_PASS_SEND_SMS_FAIL'
}